name: "Go Actions"
on: [push]
jobs:
  run:
    runs-on: self-hosted
    name: Main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: plentymarkets/actions-go
          ref: master
          token: ${{ secrets.ORGA_PAT_CICD2_FULL_REPO_AND_PACKAGES }}
          path: .github/actions
      - name: Run Action
        uses: ./.github/actions/main
